/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/predict/fire-behavior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict PMMA thin-sheet flame spread
         * @description Exploratory FireSense Physics Baseline v0. Predicts flame spread rate only inside the empirically supported Figure 2.21 domain. Requests outside the supported scientific scope return an explicit abstention.
         */
        post: operations["predict_fire_behavior_api_predict_fire_behavior_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/fire-behavior/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict and return evidence trace
         * @description Returns the FireSense prediction or abstention together with the frozen dataset identity, artifact integrity verification, canonical Figure 2.21 evidence, coefficient derivation, nearby observations, provenance policy, and uncertainty limitations.
         */
        post: operations["explain_fire_behavior_prediction_api_predict_fire_behavior_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/next-experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current next-experiment research candidate
         * @description Returns the frozen FireSense v0 research-priority matched-pair experiment candidate together with the coverage/Bayesian agreement, posterior uncertainty, evidence provenance, integrity verification, and scientific guardrails. This endpoint does not approve an experiment and does not refit the Bayesian model at request time.
         */
        get: operations["get_next_experiment_api_recommendations_next_experiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/next-experiment/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain why the next experiment is prioritized
         * @description Provides a human-readable scientific explanation of the frozen FireSense next-experiment decision, including the evidence chain, coverage/Bayesian agreement, posterior uncertainty, model limitations, and approval guardrails. No model is refitted at request time.
         */
        get: operations["explain_next_experiment_api_recommendations_next_experiment_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/figure-2-22": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return frozen Figure 2.22 comparison evidence
         * @description Returns frozen Figure 2.22 comparison-only experimental evidence.
         */
        get: operations["figure_2_22_evidence_api_api_evidence_figure_2_22_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/external-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return independent external comparison evidence
         * @description Returns the frozen Ries 2024 comparison against FireSense v0. It is not completed independent external validation.
         */
        get: operations["external_comparison_evidence_api_api_evidence_external_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return independent validation readiness status
         * @description Evaluates the frozen independent-validation acceptance protocol and screened external evidence.
         */
        get: operations["validation_readiness_api_api_evidence_validation_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-candidate/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate an independent external validation candidate
         * @description Checks a candidate holdout dataset against the frozen FireSense v0 scientific acceptance gate and runs the frozen Physics Baseline v0 on eligible rows. Passing this gate does not by itself authorize an external-validation or production-ready claim.
         */
        post: operations["validation_candidate_evaluation_api_api_evidence_validation_candidate_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-release-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return trusted independent validation release status
         * @description Returns the fail-closed FireSense independent-validation release state. Validation can only be promoted from a scientifically reviewed frozen artifact whose SHA-256 is pinned in source code.
         */
        get: operations["validation_release_status_api_api_evidence_validation_release_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-candidate/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate validation candidate performance thresholds
         * @description Runs the FireSense v0 candidate compatibility evaluator and then checks the resulting holdout metrics against the frozen pre-registered performance acceptance protocol. Passing this endpoint does not automatically promote scientific validation status.
         */
        post: operations["validation_candidate_performance_api_api_evidence_validation_candidate_performance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-source-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return frozen validation source provenance registry */
        get: operations["validation_source_registry_api_api_evidence_validation_source_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-source-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check validation-source provenance status */
        post: operations["validation_source_check_api_api_evidence_validation_source_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-dataset/import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import trusted external validation CSV evidence
         * @description Parses a candidate external holdout dataset, verifies source provenance through the frozen validation-source registry, preserves training exclusion, and only enters the direct validation and performance gates when the source has been scientifically approved.
         */
        post: operations["validation_dataset_import_csv_api_api_evidence_validation_dataset_import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-candidate/uncertainty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assess independent-validation uncertainty readiness
         * @description Checks uncertainty completeness and semantics while preserving separation between experimental, digitization and model uncertainty. FireSense v0 fails closed because its current baseline does not provide a calibrated prediction interval.
         */
        post: operations["validation_candidate_uncertainty_api_api_evidence_validation_candidate_uncertainty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/validation-scientific-review-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return scientific validation review status
         * @description Verifies the frozen validation package, performance gate, calibrated uncertainty coverage, scientific-review checks and SHA-256 bindings. This endpoint does not itself promote external-validation status.
         */
        get: operations["validation_scientific_review_status_api_api_evidence_validation_scientific_review_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgreementSummary */
        AgreementSummary: {
            /** Coverage Candidate Um */
            coverage_candidate_um: number;
            /** Bayesian Candidate Um */
            bayesian_candidate_um: number;
            /** Absolute Difference Um */
            absolute_difference_um: number;
            /** Relative Difference Percent */
            relative_difference_percent: number;
            /** Within One Percent */
            within_one_percent: boolean;
        };
        /** ArtifactIntegritySummary */
        ArtifactIntegritySummary: {
            /** Dataset Sha256 Verified */
            dataset_sha256_verified: boolean;
            /** Coverage Artifact Sha256 Verified */
            coverage_artifact_sha256_verified: boolean;
            /** Bayesian Artifact Sha256 Verified */
            bayesian_artifact_sha256_verified: boolean;
        };
        /** CoefficientDerivationInfo */
        CoefficientDerivationInfo: {
            /**
             * Formula
             * @constant
             */
            formula: "V = K / tau";
            /** Coefficient K */
            coefficient_k: number;
            /**
             * Exponent
             * @default -1
             * @constant
             */
            exponent: -1;
            /**
             * Fit Space
             * @default natural_log
             * @constant
             */
            fit_space: "natural_log";
            /** Derivation */
            derivation: string;
            /** Contributing Record Count */
            contributing_record_count: number;
            /** Contributing Record Ids */
            contributing_record_ids: string[];
        };
        /** DatasetIntegrityInfo */
        DatasetIntegrityInfo: {
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version */
            dataset_version: string;
            /** Expected Sha256 */
            expected_sha256: string;
            /** Actual Sha256 */
            actual_sha256: string;
            /** Integrity Verified */
            integrity_verified: boolean;
        };
        /** DecisionTraceStep */
        DecisionTraceStep: {
            /** Order */
            order: number;
            /**
             * Stage
             * @enum {string}
             */
            stage: "evidence" | "coverage" | "bayesian" | "agreement" | "decision";
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
        };
        /** EvidenceRecordSummary */
        EvidenceRecordSummary: {
            /** Record Id */
            record_id: string;
            /** Source Id */
            source_id: string;
            /** Figure Ref */
            figure_ref: string;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            /** Thickness Um */
            thickness_um: number;
            /** Observed Spread Rate Mm S */
            observed_spread_rate_mm_s: number;
            /** Digitization Uncertainty Mm S */
            digitization_uncertainty_mm_s: number;
        };
        /** EvidenceSummary */
        EvidenceSummary: {
            /** Source Id */
            source_id: string;
            /** Figure */
            figure: string;
            /** Dataset Version */
            dataset_version: string;
            /** Dataset Sha256 */
            dataset_sha256: string;
            /** Shared Canonical Evidence */
            shared_canonical_evidence: boolean;
            /** Independent Validation */
            independent_validation: boolean;
            /**
             * External Validation
             * @constant
             */
            external_validation: "not_performed";
        };
        /** ExistingObservationSummary */
        ExistingObservationSummary: {
            /** Thickness Um */
            thickness_um: number;
            /** Absolute Distance Um */
            absolute_distance_um: number;
            /** Log Ratio Distance */
            log_ratio_distance: number;
        };
        /** ExperimentFamilySummary */
        ExperimentFamilySummary: {
            /** Material */
            material: string;
            /** Geometry Family */
            geometry_family: string;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Pressure Kpa */
            pressure_kpa: number;
            /** Matched Variable */
            matched_variable: string;
            /** Gravity Regimes */
            gravity_regimes: string[];
        };
        /** ExplainedPredictionResponse */
        ExplainedPredictionResponse: {
            result: components["schemas"]["FireBehaviorPredictionResponse"];
            evidence_trace: components["schemas"]["PredictionEvidenceTrace"];
        };
        /** ExternalComparisonEvidenceResponse */
        ExternalComparisonEvidenceResponse: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Evidence Version
             * @constant
             */
            evidence_version: "v0";
            /** Source Name */
            source_name: string;
            /** Source Doi */
            source_doi: string;
            /**
             * Figure Ref
             * @constant
             */
            figure_ref: "4";
            /**
             * Scientific Role
             * @constant
             */
            scientific_role: "independent_external_comparison_only";
            /**
             * Independent External Source
             * @constant
             */
            independent_external_source: true;
            /**
             * Numeric External Comparison Available
             * @constant
             */
            numeric_external_comparison_available: true;
            /**
             * Independent External Validation Available
             * @constant
             */
            independent_external_validation_available: false;
            /**
             * Direct External Validation Ready
             * @constant
             */
            direct_external_validation_ready: false;
            /**
             * Training Eligible Count
             * @constant
             */
            training_eligible_count: 0;
            /**
             * Independent Validation Eligible Count
             * @constant
             */
            independent_validation_eligible_count: 0;
            /** Comparison Count */
            comparison_count: number;
            /** Measurement Definition Classification */
            measurement_definition_classification: string;
            /**
             * Measurement Definition Exact Match
             * @constant
             */
            measurement_definition_exact_match: false;
            /**
             * Flow Condition Match
             * @constant
             */
            flow_condition_match: false;
            /**
             * Flow Correction Allowed
             * @constant
             */
            flow_correction_allowed: false;
            /**
             * Exact Independent Validation Source Found
             * @constant
             */
            exact_independent_validation_source_found: false;
            /** Release Validation Status */
            release_validation_status: string;
            /** Release Comparison Status */
            release_comparison_status: string;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Artifact Sha256 */
            artifact_sha256: {
                [key: string]: string;
            };
            /**
             * Artifact Sha256 Verified
             * @constant
             */
            artifact_sha256_verified: true;
            /** Guardrails */
            guardrails: string[];
            /** Comparisons */
            comparisons: components["schemas"]["ExternalComparisonRecord"][];
        };
        /** ExternalComparisonRecord */
        ExternalComparisonRecord: {
            /**
             * Gravity Context
             * @enum {string}
             */
            gravity_context: "microgravity" | "normal_gravity";
            /** External Record Id */
            external_record_id: string;
            /** Thickness Um */
            thickness_um: number;
            /** Firesense V0 Rate Mm S */
            firesense_v0_rate_mm_s: number;
            /** Ries 2024 Rate Mm S */
            ries_2024_rate_mm_s: number;
            /** External Minus Model Mm S */
            external_minus_model_mm_s: number;
            /** Relative Gap Vs Model Percent */
            relative_gap_vs_model_percent: number;
            /** Relative Gap Vs External Percent */
            relative_gap_vs_external_percent: number;
            /** Comparison Status */
            comparison_status: string;
            /**
             * Direct Validation Eligible
             * @constant
             */
            direct_validation_eligible: false;
        };
        /** Figure222DuplicateLinkage */
        Figure222DuplicateLinkage: {
            /** Matched Figure 2 21 Record Id */
            matched_figure_2_21_record_id?: string | null;
            /** Classification */
            classification?: string | null;
            /** Relationship Status */
            relationship_status?: string | null;
            /**
             * Same Run Confirmed
             * @default false
             */
            same_run_confirmed: boolean;
            /**
             * Safe For Training Join
             * @default false
             */
            safe_for_training_join: boolean;
        };
        /** Figure222EvidenceRecord */
        Figure222EvidenceRecord: {
            /** Record Id */
            record_id: string;
            /** Source Id */
            source_id: string;
            /**
             * Figure Ref
             * @constant
             */
            figure_ref: "2.22";
            /**
             * Dataset Version
             * @constant
             */
            dataset_version: "v0";
            /** Series Key */
            series_key: string;
            /** Series Label */
            series_label: string;
            /** Series Role */
            series_role?: string | null;
            /** Series Identity */
            series_identity?: string | null;
            /** Identity Status */
            identity_status?: string | null;
            /** Publication Identity */
            publication_identity?: string | {
                [key: string]: unknown;
            } | null;
            /** Gravity Context */
            gravity_context?: string | null;
            /** Gravity Status */
            gravity_status?: string | null;
            /** Source Family Status */
            source_family_status?: string | null;
            /**
             * Evidence Type
             * @constant
             */
            evidence_type: "experimental";
            /** Thickness Um */
            thickness_um: number;
            /** Observed Spread Rate Mm S */
            observed_spread_rate_mm_s: number;
            /** Digitization Uncertainty Mm S */
            digitization_uncertainty_mm_s?: number | null;
            /** Digitization Uncertainty Status */
            digitization_uncertainty_status: string;
            /** Figure Validation Status */
            figure_validation_status: string;
            /** Training Policy */
            training_policy: string;
            /**
             * Training Eligible
             * @constant
             */
            training_eligible: false;
            /**
             * Evaluation Role
             * @constant
             */
            evaluation_role: "comparison_only";
            /**
             * Independent Validation Eligible
             * @constant
             */
            independent_validation_eligible: false;
            /** Possible Duplicate With Existing Evidence */
            possible_duplicate_with_existing_evidence: boolean;
            duplicate_linkage?: components["schemas"]["Figure222DuplicateLinkage"] | null;
        };
        /** Figure222EvidenceResponse */
        Figure222EvidenceResponse: {
            /** Dataset Name */
            dataset_name: string;
            /**
             * Dataset Version
             * @constant
             */
            dataset_version: "v0";
            /** Source Id */
            source_id: string;
            /**
             * Figure Ref
             * @constant
             */
            figure_ref: "2.22";
            /**
             * Purpose
             * @constant
             */
            purpose: "comparison_only";
            /**
             * Scientific Status
             * @constant
             */
            scientific_status: "comparison_evidence_not_independent_external_validation";
            /** Figure Validation Status */
            figure_validation_status: string;
            /** Experimental Point Count */
            experimental_point_count: number;
            /**
             * Theoretical Curves Included
             * @constant
             */
            theoretical_curves_included: false;
            /**
             * Training Eligible Count
             * @constant
             */
            training_eligible_count: 0;
            /**
             * Independent Validation Eligible Count
             * @constant
             */
            independent_validation_eligible_count: 0;
            /** Digitization Uncertainty Status */
            digitization_uncertainty_status: string;
            /** Dataset Sha256 */
            dataset_sha256: string;
            /** Dataset Sha256 Verified */
            dataset_sha256_verified: boolean;
            /** Series Counts */
            series_counts: {
                [key: string]: number;
            };
            /** Gravity Context Counts */
            gravity_context_counts: {
                [key: string]: number;
            };
            /** Duplicate Linkage Class Counts */
            duplicate_linkage_class_counts: {
                [key: string]: number;
            };
            /** Guardrails */
            guardrails: string[];
            /** Records */
            records: components["schemas"]["Figure222EvidenceRecord"][];
        };
        /** FireBehaviorPredictionRequest */
        FireBehaviorPredictionRequest: {
            /**
             * Material
             * @example PMMA
             */
            material: string;
            /**
             * Geometry
             * @example thin_sheet
             */
            geometry: string;
            /**
             * Thickness Um
             * @example 200
             */
            thickness_um: number;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            /**
             * Oxygen Fraction
             * @example 0.21
             */
            oxygen_fraction: number;
            /**
             * Pressure Kpa
             * @example 101.325
             */
            pressure_kpa: number;
        };
        /** FireBehaviorPredictionResponse */
        FireBehaviorPredictionResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "predict" | "abstain";
            prediction?: components["schemas"]["PredictionValue"] | null;
            /**
             * Abstention Reasons
             * @default []
             */
            abstention_reasons: string[];
            supported_domain?: components["schemas"]["SupportedDomain"] | null;
            model: components["schemas"]["PredictionModelInfo"];
            /** Descriptive Residual Factor */
            descriptive_residual_factor?: number | null;
            /** Uncertainty Note */
            uncertainty_note: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** GravityRecommendationSummary */
        GravityRecommendationSummary: {
            /** Predicted Spread Rate Mm S */
            predicted_spread_rate_mm_s: number;
            /** Posterior Sd Log Residual */
            posterior_sd_log_residual: number;
            nearest_existing_observation: components["schemas"]["ExistingObservationSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JointUncertaintySummary */
        JointUncertaintySummary: {
            /** Matched Pair Joint Sd Log */
            matched_pair_joint_sd_log: number;
            /** One Sd Ratio Uncertainty Factor */
            one_sd_ratio_uncertainty_factor: number;
            /** Predicted Mg To Ng Spread Ratio */
            predicted_mg_to_ng_spread_ratio: number;
        };
        /** MinimumValidationScope */
        MinimumValidationScope: {
            /** Independent Source Count */
            independent_source_count: number;
            /** Minimum Independent Numeric Points */
            minimum_independent_numeric_points: number;
            /** Note */
            note: string;
        };
        /** NextExperimentExplanationResponse */
        NextExperimentExplanationResponse: {
            /** Candidate Id */
            candidate_id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Thickness Um */
            thickness_um: number;
            /**
             * Decision Status
             * @constant
             */
            decision_status: "research_priority_candidate";
            /**
             * Approval Status
             * @constant
             */
            approval_status: "not_approved";
            /**
             * Production Ready
             * @constant
             */
            production_ready: false;
            /** Why This Thickness */
            why_this_thickness: string[];
            /** Decision Trace */
            decision_trace: components["schemas"]["DecisionTraceStep"][];
            uncertainty: components["schemas"]["RecommendationUncertaintyExplanation"];
            evidence: components["schemas"]["RecommendationEvidenceExplanation"];
            /** Scientific Caveats */
            scientific_caveats: string[];
            /** Required Before Experiment Approval */
            required_before_experiment_approval: string[];
        };
        /** NextExperimentRecommendationResponse */
        NextExperimentRecommendationResponse: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Decision Status
             * @constant
             */
            decision_status: "research_priority_candidate";
            /**
             * Recommendation Status
             * @constant
             */
            recommendation_status: "bayesian_candidate_only";
            /**
             * Approval Status
             * @constant
             */
            approval_status: "not_approved";
            /**
             * Production Ready
             * @constant
             */
            production_ready: false;
            /** Thickness Um */
            thickness_um: number;
            /** Why Selected */
            why_selected: string;
            experiment_family: components["schemas"]["ExperimentFamilySummary"];
            agreement: components["schemas"]["AgreementSummary"];
            microgravity: components["schemas"]["GravityRecommendationSummary"];
            normal_gravity: components["schemas"]["GravityRecommendationSummary"];
            joint_uncertainty: components["schemas"]["JointUncertaintySummary"];
            evidence: components["schemas"]["EvidenceSummary"];
            integrity: components["schemas"]["ArtifactIntegritySummary"];
            /** Scientific Guardrails */
            scientific_guardrails: string[];
            /** Required Before Experiment Approval */
            required_before_experiment_approval: string[];
        };
        /** PredictionEvidenceTrace */
        PredictionEvidenceTrace: {
            /** Canonical Source Id */
            canonical_source_id: string;
            /** Canonical Figure Ref */
            canonical_figure_ref: string;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            dataset_integrity: components["schemas"]["DatasetIntegrityInfo"];
            coefficient_derivation: components["schemas"]["CoefficientDerivationInfo"];
            /** Nearest Evidence Records */
            nearest_evidence_records: components["schemas"]["EvidenceRecordSummary"][];
            /** Contributing Evidence Records */
            contributing_evidence_records: components["schemas"]["EvidenceRecordSummary"][];
            /** Evidence Policy */
            evidence_policy: string[];
            /** Uncertainty State */
            uncertainty_state: string[];
            /**
             * External Validation Status
             * @default not_performed
             * @constant
             */
            external_validation_status: "not_performed";
            /**
             * Production Ready
             * @default false
             * @constant
             */
            production_ready: false;
        };
        /** PredictionModelInfo */
        PredictionModelInfo: {
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Formula */
            formula: string;
            /** Coefficient K */
            coefficient_k: number;
            /** Canonical Evidence Figure */
            canonical_evidence_figure: string;
            /**
             * External Validation Status
             * @default not_performed
             * @constant
             */
            external_validation_status: "not_performed";
            /**
             * Production Ready
             * @default false
             * @constant
             */
            production_ready: false;
        };
        /** PredictionValue */
        PredictionValue: {
            /**
             * Quantity
             * @default flame_spread_rate
             * @constant
             */
            quantity: "flame_spread_rate";
            /** Value */
            value: number;
            /**
             * Unit
             * @default mm/s
             * @constant
             */
            unit: "mm/s";
        };
        /** RatioRangeSummary */
        RatioRangeSummary: {
            /** Predicted Ratio */
            predicted_ratio: number;
            /** One Sd Factor */
            one_sd_factor: number;
            /** Descriptive Lower */
            descriptive_lower: number;
            /** Descriptive Upper */
            descriptive_upper: number;
            /** Interpretation */
            interpretation: string;
        };
        /** RecommendationEvidenceExplanation */
        RecommendationEvidenceExplanation: {
            /** Source Id */
            source_id: string;
            /** Figure */
            figure: string;
            /** Dataset Version */
            dataset_version: string;
            /** Dataset Sha256 */
            dataset_sha256: string;
            /** Shared Canonical Evidence */
            shared_canonical_evidence: boolean;
            /** Independent Validation */
            independent_validation: boolean;
            /**
             * External Validation
             * @constant
             */
            external_validation: "not_performed";
            /** Interpretation */
            interpretation: string;
        };
        /** RecommendationUncertaintyExplanation */
        RecommendationUncertaintyExplanation: {
            /** Microgravity Posterior Sd Log Residual */
            microgravity_posterior_sd_log_residual: number;
            /** Normal Gravity Posterior Sd Log Residual */
            normal_gravity_posterior_sd_log_residual: number;
            /** Matched Pair Joint Sd Log */
            matched_pair_joint_sd_log: number;
            ratio_range: components["schemas"]["RatioRangeSummary"];
            /** Uncertainty Target */
            uncertainty_target: string;
            /** Interpretation */
            interpretation: string;
            /**
             * Calibration Status
             * @constant
             */
            calibration_status: "not_externally_calibrated";
        };
        /** ScientificReviewArtifactState */
        ScientificReviewArtifactState: {
            /** Validation Manifest Present */
            validation_manifest_present: boolean;
            /** Validation Evaluation Present */
            validation_evaluation_present: boolean;
            /** Validation Performance Present */
            validation_performance_present: boolean;
            /** Validation Uncertainty Present */
            validation_uncertainty_present: boolean;
            /** Scientific Review Approval Present */
            scientific_review_approval_present: boolean;
        };
        /** SupportedDomain */
        SupportedDomain: {
            /** Material */
            material: string;
            /** Geometry */
            geometry: string;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            /** Thickness Um Min */
            thickness_um_min: number;
            /** Thickness Um Max */
            thickness_um_max: number;
            /** Oxygen Fraction */
            oxygen_fraction: number;
            /** Pressure Kpa */
            pressure_kpa: number;
        };
        /** ValidationCandidateEvaluationResponse */
        ValidationCandidateEvaluationResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: string;
            /** Source Id */
            source_id: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "compatible_independent_validation_candidate" | "independent_external_comparison_only" | "insufficient_validation_scope" | "non_independent_rejected" | "outside_firesense_v0_domain";
            /** Direct Validation Gate Passed */
            direct_validation_gate_passed: boolean;
            /** Holdout Evaluation Completed */
            holdout_evaluation_completed: boolean;
            /**
             * External Validation Claim Allowed
             * @constant
             */
            external_validation_claim_allowed: false;
            /**
             * Production Ready Claim Allowed
             * @constant
             */
            production_ready_claim_allowed: false;
            /**
             * Certification Claim Allowed
             * @constant
             */
            certification_claim_allowed: false;
            /**
             * Performance Acceptance Status
             * @enum {string}
             */
            performance_acceptance_status: "thresholds_not_yet_frozen" | "not_applicable_gate_failed";
            /** Submitted Point Count */
            submitted_point_count: number;
            /** Evaluated Point Count */
            evaluated_point_count: number;
            /** Blocked Point Count */
            blocked_point_count: number;
            /** Gate Checks */
            gate_checks: components["schemas"]["ValidationGateCheck"][];
            /**
             * Metrics Role
             * @enum {string}
             */
            metrics_role: "validation_candidate_metrics" | "comparison_only_metrics" | "not_available";
            metrics: components["schemas"]["ValidationMetrics"] | null;
            /** Evaluations */
            evaluations: components["schemas"]["ValidationEvaluationRecord"][];
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationCandidateRecord */
        ValidationCandidateRecord: {
            /** Record Id */
            record_id: string;
            /** Material */
            material: string;
            /** Geometry Family */
            geometry_family: string;
            /** Thickness Um */
            thickness_um: number;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Pressure Kpa */
            pressure_kpa: number;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            /** Transport Configuration */
            transport_configuration: string;
            /** Flow Mm S */
            flow_mm_s?: number | null;
            /** Observed Spread Rate Mm S */
            observed_spread_rate_mm_s: number;
            /** Digitization Uncertainty Mm S */
            digitization_uncertainty_mm_s?: number | null;
            /** Experimental Uncertainty Mm S */
            experimental_uncertainty_mm_s?: number | null;
            /**
             * Training Eligible
             * @default false
             */
            training_eligible: boolean;
            /**
             * Validation Holdout
             * @default true
             */
            validation_holdout: boolean;
            /** Provenance Reference */
            provenance_reference: string;
        };
        /** ValidationCandidateRequest */
        ValidationCandidateRequest: {
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: string;
            source: components["schemas"]["ValidationCandidateSource"];
            /** Records */
            records: components["schemas"]["ValidationCandidateRecord"][];
        };
        /** ValidationCandidateSource */
        ValidationCandidateSource: {
            /** Source Id */
            source_id: string;
            /** Source Title */
            source_title: string;
            /** Provenance Reference */
            provenance_reference: string;
            /** Independent Publication Or Dataset */
            independent_publication_or_dataset: boolean;
            /** Independent Experimental Campaign */
            independent_experimental_campaign: boolean;
            /** Not Firesense Training Source */
            not_firesense_training_source: boolean;
            /** Not Reused Bass Ii Rows */
            not_reused_bass_ii_rows: boolean;
            /** Experimental Data Only */
            experimental_data_only: boolean;
            /** Measurement Quantity */
            measurement_quantity: string;
            /** Measurement Definition Matches */
            measurement_definition_matches: boolean;
            /** Cross Calibration Available */
            cross_calibration_available: boolean;
            /** Normal Gravity Transport Equivalence Established */
            normal_gravity_transport_equivalence_established: boolean;
            /** Uncertainty Or Variability Metadata Preserved */
            uncertainty_or_variability_metadata_preserved: boolean;
            /** Digitization Uncertainty Separate */
            digitization_uncertainty_separate: boolean;
            /** Experimental Uncertainty Separate */
            experimental_uncertainty_separate: boolean;
            /** Model Uncertainty Separate */
            model_uncertainty_separate: boolean;
        };
        /** ValidationCsvImportRequest */
        ValidationCsvImportRequest: {
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: string;
            /** Source Id */
            source_id: string;
            /** Source Title */
            source_title: string;
            /** Provenance Reference */
            provenance_reference: string;
            /** Csv Text */
            csv_text: string;
            /** Experimental Data Only */
            experimental_data_only: boolean;
            /**
             * Measurement Quantity
             * @default flame_spread_rate
             */
            measurement_quantity: string;
            /** Measurement Definition Matches */
            measurement_definition_matches: boolean;
            /**
             * Cross Calibration Available
             * @default false
             */
            cross_calibration_available: boolean;
            /**
             * Normal Gravity Transport Equivalence Established
             * @default false
             */
            normal_gravity_transport_equivalence_established: boolean;
            /** Uncertainty Or Variability Metadata Preserved */
            uncertainty_or_variability_metadata_preserved: boolean;
            /**
             * Digitization Uncertainty Separate
             * @default true
             */
            digitization_uncertainty_separate: boolean;
            /**
             * Experimental Uncertainty Separate
             * @default true
             */
            experimental_uncertainty_separate: boolean;
            /**
             * Model Uncertainty Separate
             * @default true
             */
            model_uncertainty_separate: boolean;
        };
        /** ValidationCsvImportResponse */
        ValidationCsvImportResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: string;
            /** Source Id */
            source_id: string;
            /** Imported Row Count */
            imported_row_count: number;
            /**
             * Import Status
             * @enum {string}
             */
            import_status: "provenance_review_required" | "rejected_non_independent_source" | "comparison_only_source" | "evaluated_direct_validation_candidate";
            /** Source Known */
            source_known: boolean;
            /** Source Independence Status */
            source_independence_status: string;
            /** Registry Direct Validation Eligible */
            registry_direct_validation_eligible: boolean;
            validation_evaluation: components["schemas"]["ValidationCandidateEvaluationResponse"] | null;
            /** Performance Evaluation */
            performance_evaluation: {
                [key: string]: unknown;
            } | null;
            /**
             * External Validation Claim Allowed
             * @constant
             */
            external_validation_claim_allowed: false;
            /**
             * Production Ready Claim Allowed
             * @constant
             */
            production_ready_claim_allowed: false;
            /**
             * Certification Claim Allowed
             * @constant
             */
            certification_claim_allowed: false;
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationEvaluationRecord */
        ValidationEvaluationRecord: {
            /** Record Id */
            record_id: string;
            /**
             * Gravity Regime
             * @enum {string}
             */
            gravity_regime: "microgravity" | "normal_gravity";
            /** Thickness Um */
            thickness_um: number;
            /** Observed Spread Rate Mm S */
            observed_spread_rate_mm_s: number;
            /** Predicted Spread Rate Mm S */
            predicted_spread_rate_mm_s: number | null;
            /**
             * Prediction Decision
             * @enum {string}
             */
            prediction_decision: "predict" | "abstain";
            /** Prediction Minus Observed Mm S */
            prediction_minus_observed_mm_s: number | null;
            /** Absolute Error Mm S */
            absolute_error_mm_s: number | null;
            /** Relative Error Vs Observed Percent */
            relative_error_vs_observed_percent: number | null;
            /** Abstention Reasons */
            abstention_reasons: string[];
        };
        /** ValidationGateCheck */
        ValidationGateCheck: {
            /** Check Id */
            check_id: string;
            /** Passed */
            passed: boolean;
            /** Detail */
            detail: string;
        };
        /** ValidationMetrics */
        ValidationMetrics: {
            /** Evaluated Point Count */
            evaluated_point_count: number;
            /** Mae Mm S */
            mae_mm_s: number;
            /** Rmse Mm S */
            rmse_mm_s: number;
            /** Mean Bias Mm S */
            mean_bias_mm_s: number;
            /** Mean Absolute Percentage Error Percent */
            mean_absolute_percentage_error_percent: number;
            /** Max Absolute Error Mm S */
            max_absolute_error_mm_s: number;
        };
        /** ValidationReadinessResponse */
        ValidationReadinessResponse: {
            /** Readiness Id */
            readiness_id: string;
            /**
             * Version
             * @constant
             */
            version: "v0";
            /** Validation Protocol Id */
            validation_protocol_id: string;
            /**
             * Scientific Status
             * @constant
             */
            scientific_status: "independent_external_validation_not_yet_available";
            /**
             * Independent External Validation Available
             * @constant
             */
            independent_external_validation_available: false;
            /**
             * Independent External Comparison Available
             * @constant
             */
            independent_external_comparison_available: true;
            /**
             * Exact Source Found
             * @constant
             */
            exact_source_found: false;
            /**
             * Exact Validation Source Count
             * @constant
             */
            exact_validation_source_count: 0;
            /** Screened Candidate Count */
            screened_candidate_count: number;
            /** Independent Comparison Source Count */
            independent_comparison_source_count: number;
            target: components["schemas"]["ValidationTarget"];
            minimum_validation_scope: components["schemas"]["MinimumValidationScope"];
            /** Ries 2024 Classification */
            ries_2024_classification: string;
            /**
             * Ries 2024 Direct Validation Eligible
             * @constant
             */
            ries_2024_direct_validation_eligible: false;
            /** Ries 2024 Blocking Reasons */
            ries_2024_blocking_reasons: string[];
            /**
             * Production Ready Claim Allowed
             * @constant
             */
            production_ready_claim_allowed: false;
            /**
             * Certification Claim Allowed
             * @constant
             */
            certification_claim_allowed: false;
            /** Acceptance Criteria Sha256 */
            acceptance_criteria_sha256: string;
            /** Source Screening Sha256 */
            source_screening_sha256: string;
            /**
             * Artifact Sha256 Verified
             * @constant
             */
            artifact_sha256_verified: true;
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationReleaseStatusResponse */
        ValidationReleaseStatusResponse: {
            /** Release Status Id */
            release_status_id: string;
            /**
             * Version
             * @constant
             */
            version: "v0";
            /**
             * Scientific Status
             * @enum {string}
             */
            scientific_status: "independent_external_validation_not_yet_available" | "frozen_candidate_pending_scientific_review" | "review_approved_pending_release_promotion" | "independent_external_validation_approved";
            /** Frozen Candidate Available */
            frozen_candidate_available: boolean;
            /** Scientific Review Approved */
            scientific_review_approved: boolean;
            /** Approved Artifact Hash Frozen In Code */
            approved_artifact_hash_frozen_in_code: boolean;
            /** Independent External Validation Available */
            independent_external_validation_available: boolean;
            /**
             * Production Ready Claim Allowed
             * @constant
             */
            production_ready_claim_allowed: false;
            /**
             * Certification Claim Allowed
             * @constant
             */
            certification_claim_allowed: false;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationScientificReviewStatusResponse */
        ValidationScientificReviewStatusResponse: {
            /** Review Status Id */
            review_status_id: string;
            /**
             * Version
             * @constant
             */
            version: "v0";
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "no_frozen_validation_package" | "frozen_package_incomplete" | "pending_scientific_review" | "review_artifact_not_approved" | "review_approved_pending_release_promotion";
            artifacts: components["schemas"]["ScientificReviewArtifactState"];
            /** Artifact Integrity Verified */
            artifact_integrity_verified: boolean;
            /** Scientific Review Approved */
            scientific_review_approved: boolean;
            /** Performance Gate Passed */
            performance_gate_passed: boolean;
            /** Uncertainty Coverage Verified */
            uncertainty_coverage_verified: boolean;
            /**
             * External Validation Claim Allowed
             * @constant
             */
            external_validation_claim_allowed: false;
            /**
             * Production Ready Claim Allowed
             * @constant
             */
            production_ready_claim_allowed: false;
            /**
             * Certification Claim Allowed
             * @constant
             */
            certification_claim_allowed: false;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationSourceCheckRequest */
        ValidationSourceCheckRequest: {
            /** Source Id */
            source_id: string;
        };
        /** ValidationSourceCheckResponse */
        ValidationSourceCheckResponse: {
            /** Source Id */
            source_id: string;
            /** Known Source */
            known_source: boolean;
            /** Independence Status */
            independence_status: string;
            /** Current Role */
            current_role: string;
            /** Direct Validation Eligible */
            direct_validation_eligible: boolean;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Registry Sha256 */
            registry_sha256: string;
            /** Artifact Sha256 Verified */
            artifact_sha256_verified: boolean;
        };
        /** ValidationSourceRegistryEntry */
        ValidationSourceRegistryEntry: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Doi */
            doi?: string | null;
            /** Reference */
            reference?: string | null;
            /** Campaign */
            campaign: string;
            /** Independence Status */
            independence_status: string;
            /** Current Role */
            current_role: string;
            /** Direct Validation Eligible */
            direct_validation_eligible: boolean;
            /** Blocking Reasons */
            blocking_reasons: string[];
        };
        /** ValidationSourceRegistryResponse */
        ValidationSourceRegistryResponse: {
            /** Registry Id */
            registry_id: string;
            /** Version */
            version: string;
            /** Registry Sha256 */
            registry_sha256: string;
            /** Artifact Sha256 Verified */
            artifact_sha256_verified: boolean;
            /** Firesense Training Source Ids */
            firesense_training_source_ids: string[];
            /** Sources */
            sources: components["schemas"]["ValidationSourceRegistryEntry"][];
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationTarget */
        ValidationTarget: {
            /** Material */
            material: string;
            /** Geometry Family */
            geometry_family: string;
            /** Thickness Um */
            thickness_um: number;
            /** Oxygen Percent */
            oxygen_percent: number;
            /** Pressure Kpa */
            pressure_kpa: number;
            /** Microgravity Configuration */
            microgravity_configuration: string;
            /** Microgravity Flow Mm S */
            microgravity_flow_mm_s: number;
            /** Independent Campaign Required */
            independent_campaign_required: boolean;
        };
        /** ValidationUncertaintyAssessmentRequest */
        ValidationUncertaintyAssessmentRequest: {
            candidate: components["schemas"]["ValidationCandidateRequest"];
            /**
             * Experimental Uncertainty Kind
             * @enum {string}
             */
            experimental_uncertainty_kind: "standard_deviation" | "standard_error" | "confidence_interval_half_width" | "range_half_width" | "source_reported_unspecified" | "not_available";
            /** Experimental Uncertainty Confidence Level Percent */
            experimental_uncertainty_confidence_level_percent?: number | null;
            /**
             * Digitization Uncertainty Kind
             * @enum {string}
             */
            digitization_uncertainty_kind: "absolute_bound" | "method_sensitivity_bound" | "pixel_calibration_bound" | "source_reported_unspecified" | "not_available";
        };
        /** ValidationUncertaintyAssessmentResponse */
        ValidationUncertaintyAssessmentResponse: {
            /** Compatibility Gate Passed */
            compatibility_gate_passed: boolean;
            /** Evaluated Point Count */
            evaluated_point_count: number;
            /** Rows With Experimental Uncertainty */
            rows_with_experimental_uncertainty: number;
            /** Rows With Digitization Uncertainty */
            rows_with_digitization_uncertainty: number;
            /** Experimental Uncertainty Completeness Fraction */
            experimental_uncertainty_completeness_fraction: number;
            /** Digitization Uncertainty Completeness Fraction */
            digitization_uncertainty_completeness_fraction: number;
            /** Uncertainty Categories Separate */
            uncertainty_categories_separate: boolean;
            /** Calibrated Prediction Interval Available */
            calibrated_prediction_interval_available: boolean;
            /**
             * Uncertainty Readiness Status
             * @enum {string}
             */
            uncertainty_readiness_status: "blocked_compatibility_gate" | "blocked_incomplete_experimental_uncertainty" | "blocked_experimental_uncertainty_semantics" | "blocked_no_calibrated_prediction_interval";
            /** Coverage Verification Passed */
            coverage_verification_passed: boolean;
            /** Uncertainty Calibration Claim Allowed */
            uncertainty_calibration_claim_allowed: boolean;
            /** External Validation Claim Allowed */
            external_validation_claim_allowed: boolean;
            /** Production Ready Claim Allowed */
            production_ready_claim_allowed: boolean;
            /** Certification Claim Allowed */
            certification_claim_allowed: boolean;
            /** Diagnostics */
            diagnostics: components["schemas"]["ValidationUncertaintyRowDiagnostic"][];
            /** Guardrails */
            guardrails: string[];
        };
        /** ValidationUncertaintyRowDiagnostic */
        ValidationUncertaintyRowDiagnostic: {
            /** Record Id */
            record_id: string;
            /** Absolute Model Error Mm S */
            absolute_model_error_mm_s: number | null;
            /** Experimental Uncertainty Mm S */
            experimental_uncertainty_mm_s: number | null;
            /** Digitization Uncertainty Mm S */
            digitization_uncertainty_mm_s: number | null;
            /** Absolute Error To Experimental Uncertainty Ratio */
            absolute_error_to_experimental_uncertainty_ratio: number | null;
            /** Absolute Error To Digitization Uncertainty Ratio */
            absolute_error_to_digitization_uncertainty_ratio: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    predict_fire_behavior_api_predict_fire_behavior_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FireBehaviorPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireBehaviorPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_fire_behavior_prediction_api_predict_fire_behavior_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FireBehaviorPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainedPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_experiment_api_recommendations_next_experiment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextExperimentRecommendationResponse"];
                };
            };
        };
    };
    explain_next_experiment_api_recommendations_next_experiment_explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextExperimentExplanationResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    figure_2_22_evidence_api_api_evidence_figure_2_22_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Figure222EvidenceResponse"];
                };
            };
        };
    };
    external_comparison_evidence_api_api_evidence_external_comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalComparisonEvidenceResponse"];
                };
            };
        };
    };
    validation_readiness_api_api_evidence_validation_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReadinessResponse"];
                };
            };
        };
    };
    validation_candidate_evaluation_api_api_evidence_validation_candidate_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationCandidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationCandidateEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_release_status_api_api_evidence_validation_release_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReleaseStatusResponse"];
                };
            };
        };
    };
    validation_candidate_performance_api_api_evidence_validation_candidate_performance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationCandidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_source_registry_api_api_evidence_validation_source_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationSourceRegistryResponse"];
                };
            };
        };
    };
    validation_source_check_api_api_evidence_validation_source_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationSourceCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationSourceCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_dataset_import_csv_api_api_evidence_validation_dataset_import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationCsvImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationCsvImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_candidate_uncertainty_api_api_evidence_validation_candidate_uncertainty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationUncertaintyAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationUncertaintyAssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_scientific_review_status_api_api_evidence_validation_scientific_review_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationScientificReviewStatusResponse"];
                };
            };
        };
    };
}
